prompt --install
@@application/set_environment.sql
@@application/delete_application.sql
@@application/create_application.sql
@@application/user_interfaces.sql
@@workspace/credentials/loginapexsfc_dev.sql
@@workspace/credentials/app_101_push_notifications_credentials.sql
@@workspace/credentials/logingoogle.sql
@@workspace/credentials/app_112_push_notifications_credentials.sql
@@application/shared_components/navigation/lists/menu_de_navegação.sql
@@application/shared_components/navigation/lists/barra_de_navegação.sql
@@application/shared_components/navigation/listentry.sql
@@application/shared_components/files/manuais_manual_de_analise_de_inventario_lista_de_bens_da_antaq_versao_final_pdf.sql
@@application/shared_components/files/manuais_guia_api_sispat_latex_pdf.sql
@@application/shared_components/files/css_util_min_css.sql
@@application/shared_components/files/js_util_min_js.sql
@@application/shared_components/files/icons_icone_de_pdf_png.sql
@@application/shared_components/files/apex_data_pkg_sispat_arquivos_bens_744251_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_capitulo_560062_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_conta_contabil_462357_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_inventario_bens_656308_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_posicoes_96493_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_representante_304631_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_representante_emp_349718_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_status_bem_82082_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_subposicoes_139746_zip.sql
@@application/shared_components/files/apex_data_pkg_sispat_api_keys_818015_zip.sql
@@application/shared_components/files/icons_app_icon_32_png.sql
@@application/shared_components/files/icons_app_icon_144_rounded_png.sql
@@application/shared_components/files/icons_app_icon_192_png.sql
@@application/shared_components/files/icons_app_icon_256_rounded_png.sql
@@application/shared_components/files/icons_app_icon_512_png.sql
@@application/shared_components/files/js_util_js.sql
@@application/shared_components/files/js_jquery_maskedinput_js.sql
@@application/shared_components/files/js_jquery_maskedinput_min_js.sql
@@application/shared_components/files/css_util_css.sql
@@application/plugin_settings.sql
@@application/shared_components/security/authorizations/autoridade_portuaria.sql
@@application/shared_components/security/authorizations/administração.sql
@@application/shared_components/security/app_access_control/autoridade_portuaria.sql
@@application/shared_components/security/app_access_control/administrador.sql
@@application/shared_components/navigation/navigation_bar.sql
@@application/shared_components/logic/application_processes/gerar_zip.sql
@@application/shared_components/logic/application_settings.sql
@@application/shared_components/navigation/tabs/standard.sql
@@application/shared_components/navigation/tabs/parent.sql
@@application/shared_components/user_interface/lovs/fonte_de_recurso.sql
@@application/shared_components/user_interface/lovs/unidade_de_medida.sql
@@application/shared_components/user_interface/lovs/access_roles.sql
@@application/shared_components/user_interface/lovs/capitulo.sql
@@application/shared_components/user_interface/lovs/conta_contabil.sql
@@application/shared_components/user_interface/lovs/empresa.sql
@@application/shared_components/user_interface/lovs/estado_de_conservação.sql
@@application/shared_components/user_interface/lovs/grupo_de_bens.sql
@@application/shared_components/user_interface/lovs/histórico.sql
@@application/shared_components/user_interface/lovs/lista_posicoes.sql
@@application/shared_components/user_interface/lovs/lov_empresas_cnpj_unificada.sql
@@application/shared_components/user_interface/lovs/lov_empresas_para_nova_key.sql
@@application/shared_components/user_interface/lovs/lov_minhas_empresas_vinculadas.sql
@@application/shared_components/user_interface/lovs/modalidade_de_tombamento.sql
@@application/shared_components/user_interface/lovs/natureza.sql
@@application/shared_components/user_interface/lovs/outorga.sql
@@application/shared_components/user_interface/lovs/posicao.sql
@@application/shared_components/user_interface/lovs/razões_da_baixa.sql
@@application/shared_components/user_interface/lovs/situação.sql
@@application/shared_components/user_interface/lovs/subposicao.sql
@@application/shared_components/user_interface/lovs/tipo_de_bem.sql
@@application/shared_components/user_interface/lovs/vinculacao_contratual.sql
@@application/pages/page_groups.sql
@@application/comments.sql
@@application/shared_components/navigation/breadcrumbs/breadcrumb.sql
@@application/shared_components/navigation/breadcrumbentry.sql
@@application/shared_components/user_interface/templates/popuplov.sql
@@application/shared_components/user_interface/themes.sql
@@application/shared_components/user_interface/theme_style.sql
@@application/shared_components/user_interface/theme_files.sql
@@application/shared_components/user_interface/template_opt_groups.sql
@@application/shared_components/user_interface/template_options.sql
@@application/shared_components/globalization/language.sql
@@application/shared_components/globalization/translations.sql
@@application/shared_components/logic/build_options.sql
@@application/shared_components/globalization/messages.sql
@@application/shared_components/globalization/dyntranslations.sql
@@application/shared_components/automations/gerar_embeddings_em_lote.sql
@@application/shared_components/automations/limpeza_de_patrimônios_duplicados.sql
@@application/shared_components/security/authentications/loginapexsfc.sql
@@application/shared_components/security/authentications/semlogin.sql
@@application/shared_components/security/authentications/oracle_apex_accounts.sql
@@application/shared_components/security/authentications/login_apex_google.sql
@@application/shared_components/security/authentications/login_apex_microsoft.sql
@@application/shared_components/plugins/dynamic_action/com_jk64_report_google_map_directions_da.sql
@@application/shared_components/plugins/region_type/com_jk64_report_google_map_r1.sql
@@application/shared_components/plugins/dynamic_action/com_jk64_report_google_map_da_r1.sql
@@application/shared_components/plugins/dynamic_action/rw_apex_classic_report_sticky_columns.sql
@@application/shared_components/plugins/dynamic_action/rws_apex_ir_dynamic_item_update.sql
@@application/shared_components/data_loads/sispat_representante.sql
@@application/user_interfaces/combined_files.sql
@@application/pages/page_00000.sql
@@application/pages/page_00001.sql
@@application/pages/page_00005.sql
@@application/pages/page_00010.sql
@@application/pages/page_00011.sql
@@application/pages/page_00012.sql
@@application/pages/page_00013.sql
@@application/pages/page_00014.sql
@@application/pages/page_00020.sql
@@application/pages/page_00030.sql
@@application/pages/page_00031.sql
@@application/pages/page_00032.sql
@@application/pages/page_09999.sql
@@application/pages/page_20021.sql
@@application/pages/page_20022.sql
@@application/deployment/definition.sql
@@application/deployment/install/install_table_sispat.sql
@@application/deployment/install/install_data_sispat.sql
@@application/deployment/install/install_view_sispat.sql
@@application/deployment/checks.sql
@@application/deployment/buildoptions.sql
@@application/end_environment.sql
