prompt --application/deployment/install/install_view_sispat
begin
--   Manifest
--     INSTALL: INSTALL-view_sispat
--   Manifest End
wwv_flow_imp.component_begin (
 p_version_yyyy_mm_dd=>'2024.11.30'
,p_release=>'24.2.13'
,p_default_workspace_id=>141255302529213555
,p_default_application_id=>147
,p_default_id_offset=>162801967839124536
,p_default_owner=>'BENS'
);
wwv_flow_imp_shared.create_install_script(
 p_id=>wwv_flow_imp.id(192992856166332834)
,p_install_id=>wwv_flow_imp.id(162814622037096780)
,p_name=>'view_sispat'
,p_sequence=>30
,p_script_type=>'INSTALL'
,p_script_clob=>wwv_flow_string.join(wwv_flow_t_varchar2(
'  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_APEX_SISPAT_INVENTARIO_BENS" ("ID_CADASTRO_DE_BENS", "NUMERO_CONTRATO", "NUM_CNPJ_EMPRESA", "NUM_CNPJ_EMPRESA_FORMATADO", "NOME_PORTO", "CAPITULO", "POSICAO", "SUBPOSICAO", "NOME_ITEM", "COR", "FORNECEDO'
||'R", "NUMERO_REGISTRO_PATRIMONIAL", "MODALIDADE_TOMBAMENTO", "LATITUDE", "LONGITUDE", "DESTINACAO", "DATA_TOMBAMENTO", "CAPACIDADE", "UNIDADE_MEDIDA", "CAPACIDADE_UM", "ESPECIFICACAO_TECNICA", "VALOR_ORIGINAL_COMPRA", "VALOR_ORIGINAL_DE_COMPRA_FORMATA'
||'DO", "FONTE_RECURSO", "VIDA_UTIL_ANOS", "TAXA_DEPRECIACAO", "HISTORICO", "SITUACAO", "ESTADO_CONSERVACAO", "BEM_UNIAO", "BEM_REVERSIVEL", "NATUREZA", "TEMPO_UTILIZACAO", "VINCULACAO_CONTRATUAL", "TIPO_BEM", "GRUPO_BENS", "CONTA_CONTABIL", "DATA_DE_AV'
||'ALIACAO", "VALOR_JUSTO_MERCADO", "VALOR_JUSTO_DE_MERCADO_FORMATADO", "VALOR_RESIDUAL", "VALOR_RESIDUAL_FORMATADO", "DEPRECIACAO_ANUAL", "DEPRECIACAO_ANUAL_FORMATADO", "ID_MODALIDADE_EXPLORACAO", "MODALIDADE_EXPLORACAO", "ID_STATUS", "STATUS", "SIGLA_'
||'UF", "DESC_ENDERECO", "NOME_MUNICIPIO", "NOME_MODALIDADE", "DESC_RAZAO_SOCIAL", "ID_CONTRATO_ARRENDAMENTO", "NOME_AREA", "EMAILS", "COD_TRIGRAMA") AS ',
'  SELECT',
'  I.ID_CADASTRO_DE_BENS,',
'  I.NUMERO_CONTRATO,',
'  I.NUM_CNPJ,',
'  FORMATAR_CNPJ(TO_NUMBER(REGEXP_REPLACE(I.NUM_CNPJ, ''[^0-9]'', ''''))) AS NUM_CNPJ_EMPRESA_FORMATADO,',
'  P.NOME_PORTO,',
'  I.CAPITULO,',
'  I.POSICAO,',
'  I.SUBPOSICAO,',
'  I.NOME_ITEM,',
'  I.COR,',
'  I.FORNECEDOR,',
'  I.NUMERO_REGISTRO_PATRIMONIAL,',
'',
'  CASE I.MODALIDADE_TOMBAMENTO',
unistr('      WHEN 1 THEN ''Aquisi\00E7\00E3o'''),
'      WHEN 2 THEN ''Comodato''',
unistr('      WHEN 3 THEN ''Cess\00E3o'''),
'      WHEN 4 THEN ''Permuta ou Troca''',
unistr('      WHEN 5 THEN ''Doa\00E7\00E3o'''),
unistr('      WHEN 6 THEN ''Fabrica\00E7\00E3o'''),
unistr('      WHEN 7 THEN ''Incorpora\00E7\00E3o pr\00E9via'''),
unistr('      WHEN 8 THEN ''Transfer\00EAncia'''),
unistr('      WHEN 9 THEN ''Encampa\00E7\00E3o'''),
'      ELSE NULL',
'  END AS MODALIDADE_TOMBAMENTO,',
'',
'  I.LATITUDE,',
'  I.LONGITUDE,',
'  I.DESTINACAO,',
'  I.DATA_TOMBAMENTO,',
'  I.CAPACIDADE,',
'  I.UNIDADE_MEDIDA,',
'  I.CAPACIDADE || '' '' || I.UNIDADE_MEDIDA AS CAPACIDADE_UM,',
'  I.ESPECIFICACAO_TECNICA,',
'  I.VALOR_ORIGINAL_COMPRA,',
'  formatar_moeda(I.VALOR_ORIGINAL_COMPRA) AS VALOR_ORIGINAL_DE_COMPRA_FORMATADO,',
'',
'  CASE I.FONTE_RECURSO',
unistr('      WHEN 1 THEN ''Pr\00F3prio'''),
'      WHEN 2 THEN ''Tesouro Nacional''',
'      WHEN 3 THEN ''Tesouro Estadual''',
'      WHEN 4 THEN ''Tesouro Municipal''',
'      ELSE NULL',
'  END AS FONTE_RECURSO,',
'',
'  I.VIDA_UTIL_ANOS,',
'  I.TAXA_DEPRECIACAO,',
'',
'  CASE I.HISTORICO',
'      WHEN 1 THEN ''Tombado''',
unistr('      WHEN 2 THEN ''N\00E3o Tombado'''),
unistr('      WHEN 3 THEN ''Tombado, por\00E9m inexistente ou n\00E3o localizado'''),
unistr('      WHEN 4 THEN ''Com invent\00E1rio de transfer\00EAncia pela Uni\00E3o'''),
unistr('      WHEN 5 THEN ''Sem invent\00E1rio de transfer\00EAncia pela Uni\00E3o'''),
unistr('      WHEN 6 THEN ''Com ou sem aceite formal de transfer\00EAncia de guarda e responsabilidade.'''),
unistr('      WHEN 7 THEN ''Sem aceite formal de transfer\00EAncia de guarda e responsabilidade.'''),
'      ELSE NULL',
'  END AS HISTORICO,',
'',
'  CASE I.SITUACAO',
unistr('      WHEN 1 THEN ''Serv\00EDvel'''),
unistr('      WHEN 2 THEN ''Inserv\00EDvel - Ocioso'''),
unistr('      WHEN 3 THEN ''Inserv\00EDvel  - Antiecon\00F4mico'''),
unistr('      WHEN 4 THEN ''Inserv\00EDve - Recuper\00E1vel'''),
unistr('      WHEN 5 THEN ''Insers\00EDvel - Irrecuper\00E1vel'''),
'      ELSE NULL',
'  END AS SITUACAO,',
'',
'  CASE I.ESTADO_CONSERVACAO',
'      WHEN 1 THEN ''Novo''',
'      WHEN 2 THEN ''Excelente''',
'      WHEN 3 THEN ''Bom''',
'      WHEN 4 THEN ''Regular''',
unistr('      WHEN 5 THEN ''P\00E9ssimo'''),
'      ELSE NULL',
'  END AS ESTADO_CONSERVACAO,',
'',
'  CASE I.BEM_UNIAO',
'      WHEN 1 THEN ''Sim''',
unistr('      WHEN 2 THEN ''N\00E3o'''),
'      ELSE NULL',
'  END AS BEM_UNIAO,',
'',
'  CASE I.BEM_REVERSIVEL',
'      WHEN 1 THEN ''Sim''',
unistr('      WHEN 2 THEN ''N\00E3o'''),
'      ELSE NULL',
'  END AS BEM_REVERSIVEL,',
'',
'  CASE I.NATUREZA',
unistr('      WHEN 1 THEN ''M\00F3vel'''),
unistr('      WHEN 2 THEN ''Im\00F3vel'''),
'      ELSE NULL',
'  END AS NATUREZA,',
'',
'  I.TEMPO_UTILIZACAO,',
'',
'  CASE I.VINCULACAO_CONTRATUAL',
unistr('      WHEN 1 THEN ''Remov\00EDvel'''),
unistr('      WHEN 2 THEN ''N\00E3o Remov\00EDvel'''),
'      ELSE NULL',
'  END AS VINCULACAO_CONTRATUAL,',
'',
'  CASE I.TIPO_BEM',
unistr('      WHEN 1 THEN ''Bens da Uni\00E3o - Administra\00E7\00E3o'''),
unistr('      WHEN 2 THEN ''Bens da Uni\00E3o - Opera\00E7\00E3o'''),
unistr('      WHEN 3 THEN ''Bens da Uni\00E3o - Terceiros'''),
'      WHEN 4 THEN ''Bens de Terceiros''',
unistr('      WHEN 5 THEN ''Bens Pr\00F3prios - Administra\00E7\00E3o'''),
unistr('      WHEN 6 THEN ''Bens Pr\00F3prios - Opera\00E7\00E3o'''),
'      WHEN 7 THEN ''Imobilizado em Andamento''',
'      ELSE NULL',
'  END AS TIPO_BEM,',
'',
'  CASE I.GRUPO_BENS',
'      WHEN 1 THEN ''Terrenos''',
unistr('      WHEN 2 THEN ''Edif\00EDcios e benfeitorias'''),
unistr('      WHEN 3 THEN ''Instala\00E7\00F5es'''),
unistr('      WHEN 4 THEN ''M\00E1quinas'''),
'      WHEN 5 THEN ''Aparelhos''',
'      WHEN 6 THEN ''Equipamentos''',
unistr('      WHEN 7 THEN ''Equipamentos de Inform\00E1tica'''),
'      WHEN 8 THEN ''Sistemas aplicativos (softwares)''',
unistr('      WHEN 9 THEN ''M\00F3veis e utens\00EDlios'''),
unistr('      WHEN 10 THEN ''Ve\00EDculos'''),
'      WHEN 11 THEN ''Ferramentas''',
unistr('      WHEN 12 THEN ''Pe\00E7as e Conjuntos de Reposi\00E7\00E3o'''),
'      WHEN 13 THEN ''Benfeitorias em Propriedades Arrendada''',
unistr('      WHEN 14 THEN ''N\00E3o Aplic\00E1vel'''),
unistr('      WHEN 15 THEN ''Infraestrutura Mar\00EDtima'''),
'      WHEN 16 THEN ''Infraestrutura Acostagem''',
'      WHEN 17 THEN ''Infraestrutura Terrestre''',
unistr('      WHEN 18 THEN ''Armazenagem (P\00E1tios; Armaz\00E9ns; Tancagem, Silo)'''),
unistr('      WHEN 19 THEN ''Outros \2013 Armazenagem'''),
unistr('      WHEN 20 THEN ''Outros \2013 Equipamentos'''),
'      ELSE NULL',
'  END AS GRUPO_BENS,',
'',
'  I.CONTA_CONTABIL,',
'  I.DATA_AVALIACAO,',
'  I.VALOR_JUSTO_MERCADO,',
'  formatar_moeda(I.VALOR_JUSTO_MERCADO) AS VALOR_JUSTO_DE_MERCADO_FORMATADO,',
'  I.VALOR_RESIDUAL,',
'  formatar_moeda(I.VALOR_RESIDUAL) AS VALOR_RESIDUAL_FORMATADO,',
'  I.DEPRECIACAO_ANUAL,',
'  formatar_moeda(I.DEPRECIACAO_ANUAL) AS DEPRECIACAO_ANUAL_FORMATADO,',
'',
'  I.MODALIDADE_EXPLORACAO AS ID_MODALIDADE_EXPLORACAO,',
'  CASE I.MODALIDADE_EXPLORACAO',
unistr('      WHEN ''1'' THEN ''Autoridades Portu\00E1rias'''),
unistr('      WHEN ''2'' THEN ''Arrendat\00E1rios'''),
'      ELSE NULL',
'  END AS MODALIDADE_EXPLORACAO,',
'',
'  I.ID_STATUS,',
'  s.STATUS,',
'  I.SIGLA_UF,',
'',
unistr('  -- >>> Agora vindo da VW_APEX_EMPRESAS (padr\00E3o do seu exemplo)'),
'  ve.DESC_ENDERECO AS DESC_ENDERECO,',
'',
'  -- continuam da TB_EMPRESAS',
'  e.NOME_MUNICIPIO,',
'  e.NOME_MODALIDADE,',
'',
unistr('  -- no seu exemplo, "raz\00E3o social" sai como NOME_EMPRESA'),
'  ve.NOME_EMPRESA AS DESC_RAZAO_SOCIAL,',
'',
'  e.ID_CONTRATO_ARRENDAMENTO,',
'  e.NOME_AREA,',
'',
'  rep.EMAILS,',
'  p.COD_TRIGRAMA',
'',
'FROM SISPAT_INVENTARIO_BENS I',
'',
'LEFT JOIN (',
'  SELECT',
'    rc.num_cnpj,',
'    LISTAGG(r.email, '':'') WITHIN GROUP (ORDER BY r.email) AS EMAILS,',
'    LISTAGG(r.id_representante, '':'') WITHIN GROUP (ORDER BY r.id_representante) AS ID_REPRESENTANTES',
'  FROM sispat_representante_empresa rc',
'  JOIN sispat_representante r',
'    ON rc.id_representante = r.id_representante',
'  GROUP BY rc.num_cnpj',
') rep',
'  ON i.num_cnpj = rep.num_cnpj',
'',
'LEFT JOIN SISPAT_STATUS_BEM s',
'  ON I.ID_STATUS = s.ID_STATUS',
'',
'LEFT JOIN (SELECT * FROM TB_PORTOS WHERE COD_BIGRAMA = ''BR'') p',
'  ON I.COD_TRIGRAMA = P.COD_TRIGRAMA',
'',
'LEFT JOIN TB_EMPRESAS e',
'  ON e.NUM_INSCRICAO = I.NUM_CNPJ',
'',
'LEFT JOIN VW_APEX_EMPRESAS ve',
'  ON ve.NUM_CNPJ = I.NUM_CNPJ;',
'',
'  CREATE OR REPLACE FORCE EDITIONABLE VIEW "VW_APEX_SISPAT_REPRESENTANTES" ("ID_REPRESENTANTE", "NOME_REPRESENTANTE", "EMAIL", "NUM_CPF", "JSON_EMPRESAS", "LISTA_CNPJS", "JSON_API_KEYS") AS ',
'  WITH',
'  tb_empresas_agg AS (',
'    SELECT',
'      re.ID_REPRESENTANTE,',
'      JSON_ARRAYAGG(',
'        JSON_OBJECT(',
'          ''id_associacao'' VALUE re.ID_ASSOCIACAO,',
'          ''num_cnpj''      VALUE re.NUM_CNPJ,',
'          ''nome_empresa''  VALUE e.NOME_EMPRESA,',
'          ''cod_cnpj''      VALUE e.COD_CNPJ',
'          ABSENT ON NULL',
'        ) RETURNING CLOB',
'      ) AS JSON_EMPRESAS,',
'      LISTAGG(re.NUM_CNPJ, '', '') WITHIN GROUP (ORDER BY re.NUM_CNPJ) AS LISTA_CNPJS',
'    FROM SISPAT_REPRESENTANTE_EMPRESA re',
'    LEFT JOIN VW_APEX_EMPRESAS e ON re.NUM_CNPJ = e.NUM_CNPJ',
'    GROUP BY re.ID_REPRESENTANTE',
'  ),',
'',
'  tb_keys_agg AS (',
'    SELECT',
'      re.ID_REPRESENTANTE,',
'      JSON_ARRAYAGG(',
'        JSON_OBJECT(',
'          ''id_key''        VALUE k.ID_KEY,',
'          ''id_associacao'' VALUE k.ID_ASSOCIACAO,',
'          ''key_name''      VALUE k.KEY_NAME,',
'          ''api_key''       VALUE k.API_KEY,',
'          ''num_cnpj_key''  VALUE re.NUM_CNPJ',
'          ABSENT ON NULL',
'        ) RETURNING CLOB',
'      ) AS JSON_API_KEYS',
'    FROM SISPAT_API_KEYS k',
'    JOIN SISPAT_REPRESENTANTE_EMPRESA re',
'      ON k.ID_ASSOCIACAO = re.ID_ASSOCIACAO',
'    GROUP BY re.ID_REPRESENTANTE',
'  )',
'',
'SELECT',
'  r.ID_REPRESENTANTE,',
'  r.NOME_REPRESENTANTE,',
'  r.EMAIL,',
'  r.NUM_CPF,',
'  COALESCE(emp.JSON_EMPRESAS, TO_CLOB(''[]'')) AS JSON_EMPRESAS,',
'  emp.LISTA_CNPJS,',
'  COALESCE(key.JSON_API_KEYS, TO_CLOB(''[]'')) AS JSON_API_KEYS',
'FROM SISPAT_REPRESENTANTE r',
'LEFT JOIN tb_empresas_agg emp ON r.ID_REPRESENTANTE = emp.ID_REPRESENTANTE',
'LEFT JOIN tb_keys_agg key     ON r.ID_REPRESENTANTE = key.ID_REPRESENTANTE; '))
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(192992934198332836)
,p_script_id=>wwv_flow_imp.id(192992856166332834)
,p_object_owner=>'WKSP_SFCDEV'
,p_object_type=>'VIEW'
,p_object_name=>'VW_APEX_SISPAT_INVENTARIO_BENS'
);
wwv_flow_imp_shared.create_install_object(
 p_id=>wwv_flow_imp.id(192993123760332836)
,p_script_id=>wwv_flow_imp.id(192992856166332834)
,p_object_owner=>'WKSP_SFCDEV'
,p_object_type=>'VIEW'
,p_object_name=>'VW_APEX_SISPAT_REPRESENTANTES'
);
wwv_flow_imp.component_end;
end;
/
